### ISSUE TITLE
Only autoscroll when I deactivate then reactivate autoscroll

### ISSUE THREAD

**Issue by lepinekong** [PejmanNik/vscode-autoScroll#1]
I am exporting stock data from this metatrader indicator https://gist.github.com/lepinekong/9a53459b05ac5ed999883eb4a3cb6488

When opening the file, I have to deactivate then reactivate autoscroll to make it go to the end. And during the session, it doesn't take into account new data added to the file, I have to close and reopen the file.

**Comment by PejmanNik** [comment]
Hello @lepinekong 
Thank you for using autoScroll.

> When opening the file, I have to deactivate then reactivate autoscroll to make it go to the end

I will check and fix it until tomorrow.

>And during the session, it doesn't take into account new data added to the file, I have to close and reopen the file.

This extension does not do anything about reload file, it is done by vscode. autoscroll just scroll done after any reload.
 I suggest you see https://github.com/Microsoft/vscode/issues/21252

**Comment by PejmanNik** [comment]
@lepinekong  Fixed in version 1.0.2
