### ISSUE TITLE
Keep column position

### ISSUE THREAD

**Issue by svbauer** [PejmanNik/vscode-autoScroll#10]
Useful tool - thanks!
Is it possible to keep the position of the horizontal scollbar (i.e. the visible columns) after auto scrolling? Sometimes I need to scroll a bit to the right to see what is going on (e.g. when docker containers are downloaded and progress bar is shown...). Would be nice if auto scroll would not always jump to first column after refreshing.
Is that configurable? 

Best,
Sven

**Comment by PejmanNik** [comment]
Hello, Thank you 👍
It is completely possible. but unfortunately, it is not implemented in this extension. I'm open to PR on this and I can help if you need any.

Thank you

**Comment by PejmanNik** [comment]
Please check with the last version (1.1.0); it must have been fixed.
