### ISSUE TITLE
On Windows 10, Not AutoScrolling When VSCode Inactive And Watching Remote Log File

### ISSUE THREAD

**Issue by pcleckler** [PejmanNik/vscode-autoScroll#11]
When VSCode is not the active window, auto-scrolling stops for remote files.  Conditions attributing to this may be Windows 10 and the fact that the log is being accessed via a Windows Share.  It DOES NOT seem to matter if a mapped drive is used, or a full UNC path is used for the share.

**Comment by PejmanNik** [comment]
Does VSCode reload the last changes automatically from that remote files?

**Comment by PejmanNik** [comment]
Please feel free to reopen if you have any updates
