### ISSUE TITLE
Split Editors: non .log file is scrolled

### ISSUE THREAD

**Issue by Brains** [PejmanNik/vscode-autoScroll#14]
Have two split editors opened at the same time, with `.log` and `.fs` files.

The settings `autoscroll.autoScrollAllOpenedFiles` is disabled

<img src="https://user-images.githubusercontent.com/5301844/151583794-64b862b5-c032-4cc7-a652-68decd1a1414.png" width="300">

When `.log` editor is active, auto scroll works fine, as indented.

If activate `.fs` editor, auto scroll still works on each change, which seems to be a bug, have to disable it manually each time. 
On the screen below the cursor is inside `.fs` file while `Auto Scroll` is still active.

![image](https://user-images.githubusercontent.com/5301844/151586407-0f47bb5e-bde2-4d9d-8a2b-6cc920f20c44.png)

If there is a single editor opened, switching between these files by `Ctrl+Tab` deactivates `Auto Scroll` in `.fs` file, as expected.

Saw #3, very similar, but it was about two different `.log` files, while current issue is about files with different extensions.

**Comment by LiveFreeAndRoam** [comment]
I also see AutoScroll being automatically enabled for non-log files (e.g. `.conf`, `.py` and I think others too).  Worse, it seems to happen in a rather inconsistent fashion, eg. not all `.py` files result in AutoScroll.  I'm wondering whether there is some sort of dynamic determination whether the file is a log file.

I'm using it on a Remote SSH VScode instance.

Not sure it matters, but I have two additional file associations for log files in my `settings.json`....

```
  "files.associations": {
    "**/*.html": "html",
    "**/*.sample": "bitbake",
    "**/log.*": "log",
    "**/*_log": "log",
    "**/requirements{/**,*}.{txt,in}": "pip-requirements",
    "**/run.*": "bitbake",
    "**/templates/**/*": "django-txt",
    "**/templates/**/*.html": "django-html"
  },
```
My settings `autoscroll.autoScrollAllOpenedFiles` is disabled.

If this tool wasn't so useful, I would not have persisted with it.  Hopefully, this can be addressed soon.  Let me know if you need more info.

**Comment by PejmanNik** [comment]
Please check with the last version (1.1.0); it must have been fixed. Feel free to reopen the issue.

**Comment by Brains** [comment]
Thank you. Have different setup right now, not able to check. But will do that right after come back.
