### ISSUE TITLE
Where is the setting (key) for enable the extension for various file types or globally

### ISSUE THREAD

**Issue by DoCode** [PejmanNik/vscode-autoScroll#2]

**Comment by PejmanNik** [comment]
Hi. Thank you for using.
Right now there is no option for this. You need manually turn it on in each file.
 I'm open to PR. But why you need active auto scroll globally?

**Comment by DoCode** [comment]
@PejmanNik thanks.  
We found it annoying, to first enable the scrolling and then toggling it on and off when we need it.  
A onetime command would also nice. Toggle on/off, without the need of enabling first.

**Comment by PejmanNik** [comment]
Thank you
Ok, I'll work on add better settings.
But enabling auto scroll with command also make it active.

**Comment by PejmanNik** [comment]
I do some research and for now, there is no API to active extension based on the user setting.
see this: [#55299](https://github.com/Microsoft/vscode/issues/55299)

for now, active extension ( with a command) will enable it also. if there is another format except '.log' that you need this extension to be activated automatically, please let me know.

Thank you
