### ISSUE TITLE
AutoScroll not work when update time of the file is too long!

### ISSUE THREAD

**Issue by nkien0204** [PejmanNik/vscode-autoScroll#24]
If I try to update to a file after every second, everything works OK. But when I try with 4 or 5 seconds, It can not auto scroll!

**Comment by PejmanNik** [comment]
So it will show the latest update but no scroll to the end? Can you please create a short gif/video of the issue?

**Comment by nkien0204** [comment]
If I keep watching this file, It will not scroll. But when I close and reopen this file, It update and scroll to the end!!

**Comment by PejmanNik** [comment]
hmm, can't see how it can happen, Can you please create a short gif/video that shows the issue?

**Comment by nkien0204** [comment]
my program will write into a log file after every second and in 20 seconds it will be closed. And when I turn on AS feature, It didn't update the log content, just updated when I reopen this file or close it.

https://user-images.githubusercontent.com/44253178/209441680-48fa6e2e-50da-4857-867c-064b5796ed13.mov

**Comment by PejmanNik** [comment]
I see, The AS doesn't do anything regarding reloading the file content, it will just change the scroller position on reloads that **happened by the VS code**. I think you can create an issue in the VS code repo about the issue.

**Comment by nkien0204** [comment]
so you think it's a issue from VS Code?

**Comment by PejmanNik** [comment]
at least It is not this extension issue, the content reloads logic is handed by VS code itself. you can start by disabling all extensions and check, probably one of your extensions caused this.

Please feel free to reopen the issue if you think it is related to this extension.
