### ISSUE TITLE
Automatically enable this feature

### ISSUE THREAD

**Issue by karakarasuuuu** [PejmanNik/vscode-autoScroll#29]
Hi there, just want to say thank you for this amazing extension. It really helped me a lot during my work.
But I am wondering is it possible to let it automatically enable no matter which (log) file I open? I know that for each file, the option is reserved. But since my log files are not going to have the same name, it always bothers me that I have to turn it on each time I open a new file.
So if this option can be achieved, it will be very helpful!

**Comment by PejmanNik** [comment]
Thank you, right now the extension will get automatically active when the file language is detected as `log` In the vs code, so you can register your file extensions as `log` in the vs code setting

https://code.visualstudio.com/docs/languages/identifiers

You also need to enable this feature (`autoEnableForLogs`) in the extension setting

**Comment by karakarasuuuu** [comment]
Oh wow thanks for that update! Much appreciated!

**Comment by karakarasuuuu** [comment]
By the way in your last commit (4287c59), there is an additional **`** so the markdown syntax does not work.
![image](https://github.com/PejmanNik/vscode-autoScroll/assets/19412420/31143c2b-123d-4cc5-8749-eabf0a2d0ecf)

**Comment by PejmanNik** [comment]
You're welcome 😁
Thank you, I will fix it 🤦‍♂️
