### ISSUE TITLE
Split panes: active pane autoscrolled, not the pane that changed

### ISSUE THREAD

**Issue by sperry94** [PejmanNik/vscode-autoScroll#3]
When editing with split panes, if a file in the inactive pane increases in length, the active pane will be scrolled, not the inactive one.

**Actual Behavior:**
The `Auto Scroll` extension scrolls the active pane (static length file) to the bottom and does not scroll the file that actually changed.

**Expected Behavior:**
The `Auto Scroll` extension should scroll to the bottom of the file that actually changed and leave the static-length file alone. The scrolling should be based on the file that changed, not the active pane.

**Repro steps:**
1. Open two files and view them in separate panes.
2. Make sure one of the files is increasing in length and one remains static in length. (_It helps if the static file is long enough to require scrolling_)
3. Enable the `Auto Scroll` extension and ensure it's turned on.
4. Click into the static file and scroll to the top.
5. Wait until the file with increasing length requires a scroll.

**Comment by sperry94** [comment]
> When editing with split panes, if a file in the inactive pane increases in length, the active pane will be scrolled, not the inactive one.
> 
> **Actual Behavior:**
> The `Auto Scroll` extension scrolls the active pane (static length file) to the bottom and does not scroll the file that actually changed.
> 
> **Expected Behavior:**
> The `Auto Scroll` extension should scroll to the bottom of the file that actually changed and leave the static-length file alone. The scrolling should be based on the file that changed, not the active pane.
> 
> **Repro steps:**
> 
>     1. Open two files and view them in separate panes.
> 
>     2. Make sure one of the files is increasing in length and one remains static in length.
> 
> 
>     * it helps if the static file is long enough to require scrolling
> 
> 
>     1. Enable the `Auto Scroll` extension and ensure it's turned on.
> 
>     2. Click into the static file and scroll to the top.
> 
>     3. Wait until the file with increasing length requires a scroll.

**Comment by sperry94** [comment]
@PejmanNik I have opened a PR for this bug!

**Comment by PejmanNik** [comment]
Hi @sperry94 
Thank you. Great work.
I hope to have a release a new version tomorrow
