### ISSUE TITLE
Visual Studio Auto scroll when i paste 

### ISSUE THREAD

**Issue by Lakzvar** [PejmanNik/vscode-autoScroll#30]
I am using Visual Studio Code V 1.85.1.Sometimes when i paste a code or line visual studio will auto scroll to bottom. This just happen a few days ago and i am sure i dont's install any new extension or plugin. It's Please help it's really hinder my work

I already disable auto scroll, smart scroll or any setting that make auto scroll but nothing change. I also try reinstalling but still no change.

https://github.com/PejmanNik/vscode-autoScroll/assets/45328769/e0d602ae-20cf-4c38-8aec-3aab4bba9749

**Comment by Lakzvar** [comment]
After i do extension bisect it's confirmed that prettier is the cause of problem

**Comment by PejmanNik** [comment]
good to hear it has been solved
