### ISSUE TITLE
just active file must autoscrolled, not all opened file

### ISSUE THREAD

**Issue by PejmanNik** [PejmanNik/vscode-autoScroll#5]
> assuming I am only viewing a log file. I was under the impression that I could have the log file auto scroll, while keeping normal scroll behavior for other open files. However, if I enable auto scroll in the log file, it enables it for all open files.

**From**: _Caleb Heuer_ in marketplace.visualstudio.com review

**Comment by 68267a** [comment]
I also would like to see this fixed.

**Comment by berot3** [comment]
@PejmanNik right know all files are auto-scrolled when enabled, right?

I think it makes sense to have the option to switch between toggle for currently open file and all files.

**Comment by PejmanNik** [comment]
Thank you @accountnumber3 and  @berot3. I can't imagine any use case for scroll all open tabs. I agree this is a bug and will fix it in this week

**Comment by berot3** [comment]
Well I mean it could be useful to some in some cases. 

I got back to a real log-watcher, since filtering and high-liting seems to be more complicated in vscode than in actual log-watchers.

**Comment by PejmanNik** [comment]
Ok, so I'll add an option for this matter.
It is easy to add filtering if the vs satisfy your need

**Comment by PejmanNik** [comment]
It is fixed in v 1.0.4

`autoScrollAllOpenedFiles` option can handle the issue
