### ISSUE TITLE
Add a License to project.

### ISSUE THREAD

**Issue by prog-rajkamal** [PejmanNik/vscode-autoScroll#6]
**Issue:** the project does not have an "Open source license"
**Motivation**: I want to use the extension at my company. but lack of licensing is a blocker

**How to solve**:  Add a license file to the project and mention this at https://marketplace.visualstudio.com/items?itemName=pejmannikram.vscode-auto-scroll

Thanks in advance.

**Comment by PejmanNik** [comment]
Thank you very much but I prefer to use the MIT License. I'll add it right now.
