### ISSUE TITLE
can I auto-scroll to  not '.log' file ?

### ISSUE THREAD

**Issue by yamaken315** [PejmanNik/vscode-autoScroll#8]
This is useful function :)
I want to apply this to ".txt" file, can I do it?
(because our team's log extension is .txt)

best regards.

**Comment by PejmanNik** [comment]
Thank you 🙏
Yes, you can.

Press F1 on type "autoScroll enable"

![image](https://user-images.githubusercontent.com/18081640/82463379-00799880-9ad2-11ea-96d0-b58680c48278.png)

**Comment by yamaken315** [comment]
thank you! :) 
I sucseeded in what I have want to do !
